language: python
python:
  - "3.5"

#The important part is to install pytest, pytest-cov that allows us to generate the coverage report locally. 
#(Meaning on the Travis-CI server.) We also need to install coveralls that can submit the the report to the Coveralls.io site.  
#In the script part we need to run pytest with the --cov flag. You don't need to give a parameter to that flag, but then you might #get reports on code that is not relevant to your application. It is better to pass the directory name of your module to it (as I #did with --cov=YourModule/) so the coverage report will be restricted to code in that directory.
#You also need to tell Travis-CI to run the coveralls command after the test ran successfully. 

before_script:
  - pip install -U pytest
  - pip install pytest-cov
  - pip install coveralls
script:
  - pytest --cov=math_class test.py
after_success:
  - coveralls 
